name: Tests

on: ['push']

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        bun: [1.0.6]
        experimental: [false]
    name: 🧪 Test Sikessem using Bun-${{ matrix.bun }} under ${{ matrix.os }}

    steps:
      - name: 🚚 Fetch code
        uses: actions/checkout@v4

      - name: ⚡️ Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun }}

      - name: ⚗️ Install dependencies
        run: |
          bun install

      - name: 🍱 Compile assets
        run: bun run build
